services:
    web:
        build: ./web
        ports:
            - "3000:3000"
        environment:
            BASE_URL: http://0.0.0.0:3000
            BOT_URL: http://0.0.0.0:8000
    bot:
        build: ./bot
        environment:
            FLAG: xss{un3sc4p4bl3_s4ndb0x_can_b3_a_p4in}
            BASE_URL: http://0.0.0.0:3000
        network_mode: service:web